# -*- coding: utf-8 -*-
"""Lab 1 on Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQhnXaFuy4pP-gpgXB3sL-jzdofyPTFt
"""

#1
def shiftleft(source,k):
    for iteration in range(k):
        for i in range(0, len(source)-1):
            source[i]=source[i+1]
        source[len(source)-1]=0
source=[10,20,30,40,50,60]
shiftleft(source,3)
print(source)

#2
def leftRotate(source,k):
    for iteration in range(k):
        temp=source[0]
        for i in range(0, len(source)-1):
            source[i]=source[i+1]
        source[len(source)-1]=temp        
source=[10,20,30,40,50,60]
leftRotate(source,3)
print(source)

#3
def shifRight( source, k):
  for iteration in range(k):
    for i in range(len(source)-1,0,-1):
      source[i]=source[i-1]
    source[0]=0
  print(source)
source=[10,20,30,40,50,60] 
shifRight(source,1)

#4
def RightRotate( source, k):
  for iteration in range(k):
    temp=source[len(source)-1]
    for i in range(len(source)-1,0,-1):
      source[i]=source[i-1]
    source[0]=temp 
source=[10,20,30,40,50,60] 
RightRotate( source,3) 
print(source)

#5
def remove(source, size, indx):
    for i in range(indx,size):
        source[i]=source[i+1]
source=[10,20,30,40,50,0,0]
remove(source,5,1)
print(source)

#6
def removeAll(source, size, n):
    i=0
    while True:
        if len(source)==i:
            break
        else:
            if source[i] == n:
                remove(source, size, i)
            else:
                i+=1                
source=[10,2,30,2,50,2,2,0,0]
removeAll(source,7,2)          
print(source)

#7
a= [10, 3, 1, 2, 10,7]
new=[None]*len(a)
sum=0
for i in range(len(new)):
    sum+=a[i]
    new[i]=sum
temp=new[len(a)-1]
flag=False
for x in range(len(new)):
    if new[x]==temp-new[x]:
        flag=True
        break
    else:
        pass    
print(flag)

#8
def ArraySeries(n):   
  arr=[None]*(n*n)
  store=[None]*n
  for dig in range(1,n+1):
    store[dig-1]=dig
  arr_idx=len(arr)-1
  for i in range(n):
    store_idx=0
    while store_idx<=(n-1):
      arr[arr_idx]= store[store_idx]
      store_idx+=1
      arr_idx-=1
    store[n-1-i]=0
  return arr
print(ArraySeries(int(input("Given input: "))))

#9
def MaxBunchCount(arr):
  count=1 
  max=0  
  for i in range(len(arr)-1):
    if arr[i]==arr[i+1]:
        count+=1
        if count>max:
          max=count
    else:
      count=1   
  return max
arr=[1, 2, 2, 3, 4, 4, 4]
print(MaxBunchCount(arr))

#10
def Repetition(arr):
  #creating new array
  new=[None]*len(arr)
  check=[None]*len(arr)
  idx=0
  for i in range(len(arr)-1):
    count=1
    iteration=0
    flag_1=False
    
    while check[iteration]!=None:
      if arr[i]==check[iteration]:
        print(check[iteration])
        flag_1= True
        break
      else:
        flag_1=False
      iteration+=1
    if flag_1==False:
      for j in range(i+1,len(arr)):
        if arr[i]==arr[j]:
          count+=1
      if count>1:
        new[idx]=count
        check[idx]=arr[i]
        idx+=1
  print("new",new)
  print("check",check.)
  #repeatition checking 
  flag_2=False
  for i in range(len(new)-1):
    if new[i]!=None:
      for j in range(i+1,len(new)):
        if new[i]==new[j]:
          flag_2=True
          break
        else:
          flag_2=False
  print(flag_2) 
arr=[3,4,6,3,4,7,4,6,8,6,6] 
(Repetition(arr))